---
version: "3.7"

volumes:
  db: # this stores the neo4j database
  log: # this stores the neo4j log files

services:

  neo4j:
    image: neo4j:3.5
    volumes:
      - db:/data
      - log:/logs
    ports: # these are exposed only to allow access to neo4j browser
      - "7474:7474"
      - "7687:7687"
    environment:
      # username/password for default neo4j and graph-data-web user:
      NEO4J_AUTH: "neo4j/demo"

  graph-data-web:
    build: ./
    depends_on:
      - neo4j
    ports:
      - "8080:8080"
    environment:
      neo4j_url: "bolt://neo4j"
